---

- name: Add nodesource apt_keys
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present

- apt_repository:
    repo: "deb https://deb.nodesource.com/node_7.x {{ ansible_distribution_release }} main"
    state: present

- name: "Including distro-specific variables"
  include_vars: "vars_{{ ansible_distribution }}.yml"
  when: ansible_distribution in [ 'Ubuntu' ]
  
- name: "Setting things up for {{ ansible_distribution }}"
  include: "setup_{{ ansible_distribution }}.yml"
  when: ansible_distribution in [ 'Ubuntu' ]
 
# Setup UFW

- name: "Ensure UFW is enabled and denies all traffic by default"
  ufw:
    state: enabled
    policy: deny

- name: "Ensure UFW allows TCP traffic on ports 22, 25, 443."
  ufw:
    rule: allow
    port: '{{ item }}'
    proto: tcp
  with_items:
    - 22
    - 25
    - 80
    - 443

# Clone stuff

- name: Clone mailtrain from github
  git: repo=https://github.com/Mailtrain-org/mailtrain.git dest=/opt/mailtrain version={{ mailtrain_version }}

- name: Clone zone-mta from github
  git: repo=https://github.com/zone-eu/zone-mta.git dest=/opt/zone-mta version={{ mailtrain_zonemta_version }}

# Setting up the database

- name: Putting the configuration sql script
  template: src=mage-mailtrain-configure.sql.j2 dest="/opt/mailtrain/mage-mailtrain-configure.sql" mode="u=rwx,g=rx,o=rx"

- name: Patch the configuration sql scruot
  lineinfile: dest=/opt/mailtrain/setup/sql/mailtrain.sql
  args:
    regexp: '^CREATE TABLE `'
line: '^CREATE TABLE IF NOT EXISTS`'

- name: Install the database
  shell: 'mysql -u {{ mailtrain_mysql_username }} -p"{{ mailtrain_mysql_password }}" mailtrain < /opt/mailtrain/setup/sql/mailtrain.sql'

- name: Configure mailtrain
  shell: 'mysql -u {{ mailtrain_mysql_username }} -p"{{ mailtrain_mysql_password }}" mailtrain < /opt/mailtrain/mage-mailtrain-configure.sql'

- name: Removing the configuration script
  file:
    path: /opt/mailtrain/mage-mailtrain-configure.sql
    state: absent

# Creating users

- name: Ensuring mailtrain user is present.
  user:
    name: mailtrain

- name: Ensuring zone-mta user is present.
  user:
    name: zone-mta
    
# Putting config files

- name: "Make sure mailtrain's config.json is present."
  template:
    src: mailtrain-production.toml.j2
    dest: /opt/mailtrain/config/production.toml

- name: "Make sure mailtrain workers' config.json is present."
  template:
    src: mailtrain_workers_production.toml.j2
    dest: /opt/mailtrain/workers/reports/config/production.toml

- name: "Make sure mailtrain's logrotate conf file is present."
  template:
    src: mailtrain-logrotate
    dest: /etc/logrotate.d/mailtrain

- name: "Make sure mailtrain's config.json is present."
  template:
    src: zone-mta-production.json.j2
    dest: /opt/zone-mta/config/production.json

# NPM magic

- name: Mailtrain npm install.
  shell: npm install --no-progress --production
  args:
    chdir: /opt/mailtrain

- name: "Zone-mta npm install (1)."
  shell: npm install --no-progress --production
  args:
    chdir: /opt/zone-mta

- name: "Zone-mta npm install (2)."
  shell: npm install leveldown
  args:
    chdir: /opt/zone-mta

- name: "Ensuring propper ownership is set"
  file: path=/opt/mailtrain owner=mailtrain group=mailtrain recurse=yes

- name: "Ensuring propper ownership is set (config)"
  file: path=/opt/mailtrain/config mode=o-rwx

- name: Ensure mailtrain unitfile is set.
  shell: 'cp /opt/mailtrain/setup/mailtrain.service /etc/systemd/system/'

- name: Ensure zone-mta unitfile is set.
  shell: 'cp /opt/zone-mta/setup/zone-mta.service /etc/systemd/system/'

- file:
    path: /var/data/zone-mta/mailtrain
    state: directory
    owner: zone-mta
    group: zone-mta
    recurse: yes

- name: Make sure zone-mta is enabled
  service: name=zone-mta enabled=yes state=restarted

- name: Make sure zone-mta is enabled
  service: name=mailtrain enabled=yes state=restarted
